wealthy = Project.create(name: 'Wealth Building')
wealthy.tasks.create(name: 'Get rich quick')
wealthy.tasks.create(name: 'Write a book')

happy = Project.create(name: 'Be Happy')
happy.tasks.create(name: 'Buy a puppy')
happy.tasks.create(name: 'Dance in the rain')
happy.tasks.create(name: 'Dance in the snow')
happy.tasks.create(name: 'Walk on water')
happy.tasks.create(name: 'Just Blog It')
happy.tasks.create(name: 'Play tennis')
happy.tasks.create(name: 'Make fun of Donald Trump')
happy.tasks.create(name: 'Walk on moon')
